{% set name = "iterative_solver" %}
{% set version = "0.10.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/molpro/iterative-solver/archive/refs/tags//{{ version }}.tar.gz
  sha256: 529d88823449ee94e961558afbdc093de8bb8e6ca9d125144613fafd9212d245

build:
  skip: true  # [win]
  script:
    - export VERSION={{ version }}
    - cmake ${CMAKE_ARGS} -DCMAKE_INSTALL_PREFIX=$PREFIX  -DCMAKE_CXX_FLAGS=-fPIC  -DCMAKE_BUILD_TYPE=Release  -DDEPENDENCYMANAGER_FETCHCONTENT=OFF  -DLINEARALGEBRA_ARRAY_HDF5=OFF -DLINEARALGEBRA_ARRAY_GA=OFF  -DFORTRAN=OFF -DBUILD_SHARED_LIBS=ON -DLIBRARY_ONLY=ON -B cmake-build -S .
    - cmake --build cmake-build --config Release -t install
    - echo '__version__ = "'$VERSION'"' > python/iterative_solver/_version.py
    - cd python && {{ PYTHON }} -m pip install . -vvv
  number: 1

requirements:
  build:
    - python     # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.0                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - numpy  # [build_platform != target_platform]
    - cmake >=3.14
    - make
    - pip
  host:
    - python
    - pip
    - cython >=3.0
    - numpy
    - mpich
    - eigen
    - liblapacke
    - libblas
  run:
    - python

test:
  imports:
    - iterative_solver
  requires:
    - pip
  commands:
    - pip check
    # these could eventually move into a separate library ouput
    - test -f $PREFIX/lib/libmolpro-iterative-solver${SHLIB_EXT}    # [unix]
    - test -f $PREFIX/lib/libmolpro-profiler${SHLIB_EXT}            # [unix]
    - test -f $PREFIX/lib/libmolpro-utilities${SHLIB_EXT}           # [unix]

about:
  home: https://github.com/molpro/iterative-solver
  summary: |
    Implements iterative solvers for linear and non-linear problems and distributed arrays for HPC.
  description: Implements iterative solvers for eigenvalue problem, linear equations, optimisation (L-BFGS) and non-linear equations (DIIS)
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://molpro.github.io/iterative-solver
  dev_url: https://github.com/molpro/iterative-solver

extra:
  recipe-maintainers:
    - pjknowles
    - molpro-owner
